export { default as Frame11png } from "./Frame 11.png";
export { default as Frame1 } from "./Frame 11 (1).png";
export { default as Frame2 } from "./Frame 11 (2).png";
export { default as Frame3 } from "./Frame 11 (3).png";
export { default as Frame4 } from "./Frame 11 (4).png";
export { default as Frame5 } from "./Frame 11 (5).png";
export { default as Frame6 } from "./Frame 11 (6).png";
export { default as Frame7 } from "./Frame 97.png";
export { default as Frame8 } from "./Frame 98.png";
export { default as Frame9 } from "./Frame 99.png";
export { default as Frame10 } from "./Frame 100.png";
export { default as Frame11 } from "./Frame 160.png";
export { default as Frame12 } from "./Frame 161.png";
export { default as Frame13 } from "./Frame 163.png";
export { default as Frame14 } from "./Frame 173.png";
export { default as Frame15 } from "./Frame 174.png";
export { default as Frame16 } from "./Frame 191.png";
export { default as Frame17 } from "./Frame 97.png";
export { default as Frame18 } from "./Frame 98.png";
export { default as Frame19 } from "./Frame 99.png";
export { default as Frame20 } from "./Frame 102.png";
export { default as Frame21 } from "./Frame 103.png";
export { default as Frame22 } from "./Frame 104.png";
export { default as Frame23 } from "./Frame 165.png";
export { default as Frame24 } from "./Frame 166.png";
export { default as Frame25 } from "./Frame 167.png";
export { default as Frame26 } from "./Frame 173.png";
export { default as Frame27 } from "./Frame 174.png";
export { default as Frame28 } from "./Frame 180.png";
export { default as Frame29 } from "./Frame 181.png";
export { default as Frame30 } from "./Frame 182.png";
export { default as Frame31 } from "./Frame 191.png";
